name: LKS Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy EduNews ke Elastic Beanstalk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install dependencies
        run: npm install

      - name: Buat deployment package
        run: |
          zip -r edunews-deploy.zip . \
            --exclude "*.git*" \
            --exclude ".github/*"

      - name: Upload ke S3
        run: |
          aws s3 cp edunews-deploy.zip \
            s3://${{ secrets.S3_ARTIFACTS_BUCKET }}/edunews-${{ github.sha }}.zip

      - name: Buat application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.EB_APP_NAME }} \
            --version-label "v-${{ github.sha }}" \
            --source-bundle \
              S3Bucket=${{ secrets.S3_ARTIFACTS_BUCKET }},S3Key=edunews-${{ github.sha }}.zip

      - name: Deploy ke Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --application-name ${{ secrets.EB_APP_NAME }} \
            --environment-name ${{ secrets.EB_ENV_NAME }} \
            --version-label "v-${{ github.sha }}"

      - name: Tunggu selesai
        run: |
          aws elasticbeanstalk wait environment-updated \
            --application-name ${{ secrets.EB_APP_NAME }} \
            --environment-names ${{ secrets.EB_ENV_NAME }}
